// Units are in centimeters.

FACE_WIDTH = 10;
FACE_DEPTH = 11;
FACE_HEIGHT = 0.6;

FACE_BORDER_WIDTH = 1.5;
FACE_BORDER_DEPTH = FACE_BORDER_WIDTH;

BARS_DEPTH = FACE_DEPTH - (FACE_BORDER_DEPTH * 2);
BARS_WIDTH = FACE_WIDTH - (FACE_BORDER_WIDTH * 2);
BAR_WIDTH = BARS_WIDTH;
BAR_DEPTH = 1;

BAR_GAP = 0.4;

SUPPORT_WIDTH = BARS_WIDTH;
SUPPORT_HEIGHT = 0.2;

JAGGED_EDGE_WIDTH_OFFSET = 1;
JAGGED_EDGE_WIDTH = BAR_WIDTH - JAGGED_EDGE_WIDTH_OFFSET;
JAGGED_EDGE_DEPTH = 0.3;

